### ISSUE TITLE
Error in the last commit

### ISSUE THREAD

**Issue by darbejel** [mzfr/slicer#10]
Hello,

Thanks for this nice tool :) I'm unable to run it, here in my Win10 with Golang installed the following error is displayed:

panic: open /resources/AndroidManifest.xml: The system cannot find the path specified.

Am I missing something?

I already tested with the prebuilt binary but the issue is the same.

Thanks!

**Comment by mzfr** [comment]
Hey the issue can arise due to unpacking of apk, if you unpack with apktool then you'll have to change the path yourself in the config.yml.
See readme to find out more

**Comment by darbejel** [comment]
Hi,

Thank you, I resolved this now.
