### ISSUE TITLE
Goroutine Error

### ISSUE THREAD

**Issue by amiralkizaru** [mzfr/slicer#11]
Hello

Thank you for taking the time to create this tool
However, I encountered an issue while trying it in 
## Installation Process
go get github.com/mzfr/slice
## config
Windows 10 / WSL2
Ubuntu 18.04
Go1.14
## Issue
![issueGithub](https://user-images.githubusercontent.com/32225186/87976985-e35b4900-cac5-11ea-864b-7dc9cf665a03.jpg)

## Copied the config file into .slicer
![issue2](https://user-images.githubusercontent.com/32225186/87977058-fe2dbd80-cac5-11ea-9f52-f03d52588d37.jpg)

**Comment by mzfr** [comment]
Hey

First thing it should be 

go get github.com/mzfr/slicer

And not 
go get github.com/mzfr/slice


Also it won't work on packed apk extract it using jadx or apktool
