### ISSUE TITLE
(Windows) CreateFile /resources/AndroidManifest.xml: The system cannot find the path specified.

### ISSUE THREAD

**Issue by bbakbbak2** [mzfr/slicer#17]
When I execute slicer in binary on windows, it give me a error message "CreateFile /resources/AndroidManifest.xml: The system cannot find the path specified."

**Comment by mzfr** [comment]
If you have used `apktool` to extract the apk then please update the path in the config file.

The path fixed in the config file is for when apk is extracted using jadx.

**Comment by mzfr** [comment]
Closing this if you have any other issue then feel free to open a new issue
