### ISSUE TITLE
Error on running the tool

### ISSUE THREAD

**Issue by balook** [mzfr/slicer#3]
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
main.main()
        /home/balu/go/src/github.com/mzfr/slicer/main.go:215 +0x62e

# slicer -d ./airbnb/ -nb=false

**Comment by mzfr** [comment]
@balook Was the APK opened with `apktool` or with `jadx`? Also if you make any changes to the config.yml file then please make sure that it's in the right format.
