### ISSUE TITLE
issue running the tool

### ISSUE THREAD

**Issue by soupnatzi** [mzfr/slicer#31]
what am i doing wrong here?would love to know i have tried both right after downloading the apk and unpacking the apk with jadx and apktool:

slicer -d /root/Downloads/com.baronapp.cameo_147654_apps.evozi.com.apk
Error reading config file, Config File "config" Not Found in "[/root /root/.slicer]"panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
main.main()
	/root/slicer/main.go:264 +0xbe5

would love to know how to fix this issue.

**Comment by mzfr** [comment]
Hey, for this to run you also need a `config` file. In the Readme see the [Installation](https://github.com/mzfr/slicer#installation) section, there is an important note :)

> NOTE: Slicer uses config.yml file. So either have a file named config.yml in your current working directory or make a directory named .slicer in your $HOME and then place the config.yml file there.

The content of the config file can be seen [here](https://github.com/mzfr/slicer/blob/master/config.yml)

Also if you are unpacking with `apktool` then make sure to change the `paths` for all manifest, strings, raw and xml folder.

**Comment by soupnatzi** [comment]
ah got it :)
