### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by utkarsh24122** [mzfr/slicer#39]
![image](https://user-images.githubusercontent.com/54320208/125245805-a0b20280-e30e-11eb-9351-8d53c6766e78.png)

I am getting this error while running ``` cargo build ``` in the slicer directory.
I even tried re-installing rust

**Comment by mzfr** [comment]
Hey,

This project is far from being done. I don't know rust at all, so I'm just learning it as I make this tool. 

If you want you can use the golang version of it, which is present on the [go branch](https://github.com/mzfr/slicer/tree/go). Or you can download the binaries which are also in golang.

Thanks

**Comment by utkarsh24122** [comment]
Thanks a lot ... the golang version works perfectly 🔥👌
