### ISSUE TITLE
Search API Keys in AndroidManifest.xml

### ISSUE THREAD

**Issue by balook** [mzfr/slicer#4]
i have an apk that has api keys in android manifest file but its not outputting apikeys in manifest but only in strings.xml

it only looking for ipc calls in manifest and intents not more than that ..!

**Comment by mzfr** [comment]
Yes currently it doesn't do that. I'll make the changes for that.

**Comment by balook** [comment]
buildconfig.java These files also have sensitive data

**Comment by balook** [comment]
HTML output with multiple colours will be a gret idea to implement

**Comment by mzfr** [comment]
@balook if you have any idea then please open separate issues for those. It would be nice to keep this just for API keys lookup :smile:

**Comment by mzfr** [comment]
Fixed via https://github.com/mzfr/slicer/commit/9d287f0329b5bb8fc5d7f0b413ce34d929715c83
