### ISSUE TITLE
Report type of pinning used

### ISSUE THREAD

**Issue by mzfr** [mzfr/slicer#5]
Idea from this [tweet](https://twitter.com/MrR0Y4L3/status/1282225036040921090).

Bypassing trust manager and okhttp3 pinning is slightly different. Maybe it would be better to add a feature to report which kind of pinning is used.

**Comment by balook** [comment]
Also proguard and other obscation using information

**Comment by mzfr** [comment]
After thinking a bit more about this I feel that adding functionality as this wouldn't be that great. Because no matter what the type of pinning is used we can just bypass that using a single script.

There exists a single script([1](https://gist.github.com/akabe1/ac6029bf2315c6d95ff2ad00fb7be1fc),[2](https://gist.github.com/akabe1/5632cbc1cd49f0237cbd0a93bc8e4452)) that you can just hook and it will automatically detect which pinning is used and will bypass it for you. 

So it doesn't even matter whether we know it or not.

I'll close this for now and will think a bit more about this. If I find this somehow useful then I'll add this feature in future releases.
